name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + CUDA + DVC + CML image
    # container: docker://iterativeai/cml:0-dvc2-base1-gpu
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
    # optionally use a convenient Ubuntu LTS + CUDA + DVC + CML image
    # container: docker://iterativeai/cml:0-dvc2-base1-gpu
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1-gpu
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        
      - name: Setup Dependencies 
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'
      - name: Analyse
        env:
           repo_token :: ${{secrets.GITHUB_TOKEN }}
        run: |
          R -e 'renv::run("ClassifyData.R")'
      
      
